# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: table.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='table.proto',
  package='cronus',
  syntax='proto3',
  serialized_pb=_b('\n\x0btable.proto\x12\x06\x63ronus\"D\n\x05Table\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x1f\n\x04info\x18\x03 \x01(\x0b\x32\x11.cronus.TableInfo\"+\n\tTableInfo\x12\x1e\n\x06schema\x18\x01 \x01(\x0b\x32\x0e.cronus.Schema\"F\n\x06Schema\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12 \n\x04info\x18\x03 \x01(\x0b\x32\x12.cronus.SchemaInfo\"O\n\nSchemaInfo\x12\"\n\x03\x61ux\x18\x01 \x01(\x0b\x32\x15.cronus.SchemaAuxInfo\x12\x1d\n\x06\x66ields\x18\x02 \x03(\x0b\x32\r.cronus.Field\"L\n\rSchemaAuxInfo\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x12\n\nraw_header\x18\x02 \x01(\x0c\x12\x12\n\nraw_footer\x18\x03 \x01(\x0c\"D\n\x05\x46ield\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x1f\n\x04info\x18\x03 \x01(\x0b\x32\x11.cronus.FieldInfo\"o\n\tFieldInfo\x12!\n\x03\x61ux\x18\x01 \x01(\x0b\x32\x14.cronus.FieldAuxInfo\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x10\n\x08nullable\x18\x03 \x01(\x08\x12\x1f\n\x08\x63hildren\x18\x04 \x03(\x0b\x32\r.cronus.Field\"~\n\x0c\x46ieldAuxInfo\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12,\n\x04meta\x18\x02 \x03(\x0b\x32\x1e.cronus.FieldAuxInfo.MetaEntry\x1a+\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')
)




_TABLE = _descriptor.Descriptor(
  name='Table',
  full_name='cronus.Table',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cronus.Table.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='cronus.Table.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='cronus.Table.info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=91,
)


_TABLEINFO = _descriptor.Descriptor(
  name='TableInfo',
  full_name='cronus.TableInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='schema', full_name='cronus.TableInfo.schema', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=136,
)


_SCHEMA = _descriptor.Descriptor(
  name='Schema',
  full_name='cronus.Schema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cronus.Schema.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='cronus.Schema.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='cronus.Schema.info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=208,
)


_SCHEMAINFO = _descriptor.Descriptor(
  name='SchemaInfo',
  full_name='cronus.SchemaInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aux', full_name='cronus.SchemaInfo.aux', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fields', full_name='cronus.SchemaInfo.fields', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=289,
)


_SCHEMAAUXINFO = _descriptor.Descriptor(
  name='SchemaAuxInfo',
  full_name='cronus.SchemaAuxInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='cronus.SchemaAuxInfo.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_header', full_name='cronus.SchemaAuxInfo.raw_header', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_footer', full_name='cronus.SchemaAuxInfo.raw_footer', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=367,
)


_FIELD = _descriptor.Descriptor(
  name='Field',
  full_name='cronus.Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='cronus.Field.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='cronus.Field.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='cronus.Field.info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=437,
)


_FIELDINFO = _descriptor.Descriptor(
  name='FieldInfo',
  full_name='cronus.FieldInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aux', full_name='cronus.FieldInfo.aux', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='cronus.FieldInfo.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nullable', full_name='cronus.FieldInfo.nullable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='children', full_name='cronus.FieldInfo.children', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=550,
)


_FIELDAUXINFO_METAENTRY = _descriptor.Descriptor(
  name='MetaEntry',
  full_name='cronus.FieldAuxInfo.MetaEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='cronus.FieldAuxInfo.MetaEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='cronus.FieldAuxInfo.MetaEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=635,
  serialized_end=678,
)

_FIELDAUXINFO = _descriptor.Descriptor(
  name='FieldAuxInfo',
  full_name='cronus.FieldAuxInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='cronus.FieldAuxInfo.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta', full_name='cronus.FieldAuxInfo.meta', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FIELDAUXINFO_METAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=678,
)

_TABLE.fields_by_name['info'].message_type = _TABLEINFO
_TABLEINFO.fields_by_name['schema'].message_type = _SCHEMA
_SCHEMA.fields_by_name['info'].message_type = _SCHEMAINFO
_SCHEMAINFO.fields_by_name['aux'].message_type = _SCHEMAAUXINFO
_SCHEMAINFO.fields_by_name['fields'].message_type = _FIELD
_FIELD.fields_by_name['info'].message_type = _FIELDINFO
_FIELDINFO.fields_by_name['aux'].message_type = _FIELDAUXINFO
_FIELDINFO.fields_by_name['children'].message_type = _FIELD
_FIELDAUXINFO_METAENTRY.containing_type = _FIELDAUXINFO
_FIELDAUXINFO.fields_by_name['meta'].message_type = _FIELDAUXINFO_METAENTRY
DESCRIPTOR.message_types_by_name['Table'] = _TABLE
DESCRIPTOR.message_types_by_name['TableInfo'] = _TABLEINFO
DESCRIPTOR.message_types_by_name['Schema'] = _SCHEMA
DESCRIPTOR.message_types_by_name['SchemaInfo'] = _SCHEMAINFO
DESCRIPTOR.message_types_by_name['SchemaAuxInfo'] = _SCHEMAAUXINFO
DESCRIPTOR.message_types_by_name['Field'] = _FIELD
DESCRIPTOR.message_types_by_name['FieldInfo'] = _FIELDINFO
DESCRIPTOR.message_types_by_name['FieldAuxInfo'] = _FIELDAUXINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Table = _reflection.GeneratedProtocolMessageType('Table', (_message.Message,), dict(
  DESCRIPTOR = _TABLE,
  __module__ = 'table_pb2'
  # @@protoc_insertion_point(class_scope:cronus.Table)
  ))
_sym_db.RegisterMessage(Table)

TableInfo = _reflection.GeneratedProtocolMessageType('TableInfo', (_message.Message,), dict(
  DESCRIPTOR = _TABLEINFO,
  __module__ = 'table_pb2'
  # @@protoc_insertion_point(class_scope:cronus.TableInfo)
  ))
_sym_db.RegisterMessage(TableInfo)

Schema = _reflection.GeneratedProtocolMessageType('Schema', (_message.Message,), dict(
  DESCRIPTOR = _SCHEMA,
  __module__ = 'table_pb2'
  # @@protoc_insertion_point(class_scope:cronus.Schema)
  ))
_sym_db.RegisterMessage(Schema)

SchemaInfo = _reflection.GeneratedProtocolMessageType('SchemaInfo', (_message.Message,), dict(
  DESCRIPTOR = _SCHEMAINFO,
  __module__ = 'table_pb2'
  # @@protoc_insertion_point(class_scope:cronus.SchemaInfo)
  ))
_sym_db.RegisterMessage(SchemaInfo)

SchemaAuxInfo = _reflection.GeneratedProtocolMessageType('SchemaAuxInfo', (_message.Message,), dict(
  DESCRIPTOR = _SCHEMAAUXINFO,
  __module__ = 'table_pb2'
  # @@protoc_insertion_point(class_scope:cronus.SchemaAuxInfo)
  ))
_sym_db.RegisterMessage(SchemaAuxInfo)

Field = _reflection.GeneratedProtocolMessageType('Field', (_message.Message,), dict(
  DESCRIPTOR = _FIELD,
  __module__ = 'table_pb2'
  # @@protoc_insertion_point(class_scope:cronus.Field)
  ))
_sym_db.RegisterMessage(Field)

FieldInfo = _reflection.GeneratedProtocolMessageType('FieldInfo', (_message.Message,), dict(
  DESCRIPTOR = _FIELDINFO,
  __module__ = 'table_pb2'
  # @@protoc_insertion_point(class_scope:cronus.FieldInfo)
  ))
_sym_db.RegisterMessage(FieldInfo)

FieldAuxInfo = _reflection.GeneratedProtocolMessageType('FieldAuxInfo', (_message.Message,), dict(

  MetaEntry = _reflection.GeneratedProtocolMessageType('MetaEntry', (_message.Message,), dict(
    DESCRIPTOR = _FIELDAUXINFO_METAENTRY,
    __module__ = 'table_pb2'
    # @@protoc_insertion_point(class_scope:cronus.FieldAuxInfo.MetaEntry)
    ))
  ,
  DESCRIPTOR = _FIELDAUXINFO,
  __module__ = 'table_pb2'
  # @@protoc_insertion_point(class_scope:cronus.FieldAuxInfo)
  ))
_sym_db.RegisterMessage(FieldAuxInfo)
_sym_db.RegisterMessage(FieldAuxInfo.MetaEntry)


_FIELDAUXINFO_METAENTRY.has_options = True
_FIELDAUXINFO_METAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
